### ISSUE TITLE
Circular references between ValidityCondition and TimeValidity?

### ISSUE THREAD

**Issue by ajf2** [department-for-transport-public/D-TRO#14]
Hello, I'm trying to upload one of the sample files to the integration environment via the `dtros/createFromFile` endpoint, then download it again from the GET `dtro/{id}` endpoint.

I've successfully uploaded the file `JSON-3.2.3-example-point-dtro.json` but I'm having trouble understanding the Conditions part of the model when deserialising the response from the GET endpoint.

The first condition seems to be an empty `VehicleCondition`. That seems meaningless and should be ignored.

The part I'm stuck on is with the second condition - it seems to me that this object should be of type `ValidityCondition` (a specialism of `Condition`). It has a `timeValidity` property which in turn has a `validityCondition` property. Shouldn't the `rateTable` and `conditionSet` properties on the inner `validityCondition` be on the outer object, at the same level as `timeValidity`?

![image](https://github.com/user-attachments/assets/a6bbc716-3a00-4f91-a55f-bbe46d4eb895)

Also, as previously mentioned (https://github.com/department-for-transport-public/D-TRO/issues/12#issuecomment-2407133407), the `regulationStatus` property is not in the schema at all.

Looking at the JSON schema (and I must admit I'm no expert here), it seems that `ValidityCondition` must have at least one `TimeValidity` property and `TimeValidity` must have at least one `ValidityCondition` property, which would surely mean an endless cycle of each type referencing the other.

![image](https://github.com/user-attachments/assets/f989971c-3b75-47a7-ae73-917fe22b4946)

**Comment by JHB9876** [comment]
On behalf of DfT:

Thanks for raising this. The structure of the sample files have been corrected.

In a future version, we will aim to simplify how TimeValidity is referenced in the model and schema. At present, TimeValidity appears both as a relation to Regulation and also as a child of Condition. On review, the child of Condition representation is preferred (and is more flexible). Therefore the TimeValidity related to Regulation is considered to be deprecated and will be removed in a future release of the data specification.
