### ISSUE TITLE
Internal Server Error on both dtros/createFromFile and dtros/createFromBody

### ISSUE THREAD

**Issue by ajf2** [department-for-transport-public/D-TRO#15]
I'm receiving an HTTP 500 Internal Server Error when using either of the `dtros/createFromFile` and `dtros/createFromBody` endpoints.
In either case, my payload is as follows (the call to createFromBody reads this same text and de/serialises it first):

`{"schemaVersion":"3.2.3","data":{"Source":{"actionType":"amendment","currentTraOwner":15,"provision":[{"actionType":"fullRevoke","orderReportingPoint":"ttroTtmoByNotice","provisionDescription":"Prohibition of Waiting","reference":"A3448229-1DFA-48CD-A785-376ACB9F7C56","regulation":[{"isDynamic":false,"timeZone":"Europe/London","regulationType":"kerbsideLimitedWaiting","condition":[{"timeValidity":{"start":"1983-01-05 22:50:50","exceptionPeriod":[{"recurringSpecialDay":[{"intersectWithApplicableDays":true,"specialDayType":"matchDay"},{"intersectWithApplicableDays":false,"specialDayType":"matchDay","publicEvent":"footballMatch"}],"recurringTimePeriodOfDay":[{"startTimeOfPeriod":"17:00:00","endTimeOfPeriod":"18:00:00"}],"recurringDayWeekMonthPeriod":[{"applicableDay":["monday"],"applicableMonth":["october"]}],"startOfPeriod":"1983-01-05 22:50:50","periodName":"adipisicing incididunt Lorem","endOfPeriod":"1983-03-17 16:47:01"}],"validPeriod":[{"recurringTimePeriodOfDay":[{"startTimeOfPeriod":"07:30:00","endTimeOfPeriod":"09:00:00"},{"startTimeOfPeriod":"17:00:00","endTimeOfPeriod":"18:00:00"}],"startOfPeriod":"1985-07-01 21:12:04","recurringSpecialDay":[{"intersectWithApplicableDays":true,"specialDayType":"eventDay"},{"intersectWithApplicableDays":true,"specialDayType":"eventDay"}],"periodName":"ea et eiusmod","recurringDayWeekMonthPeriod":[{"applicableDay":["tuesday"]},{"applicableMonth":["june"],"applicableDay":["monday"]}]}],"end":"1996-01-05 22:50:50"},"rateTable":{"rateLineCollection":[{"rateLine":[{"sequence":0,"type":"flatRateTier","value":15,"durationEnd":"19:00:00"},{"sequence":1,"type":"flatRate","value":20,"maxValue":40,"durationStart":"19:00:00","incrementPeriod":"PT1H","durationEnd":"19:30:00","usageCondition":"unlimited","description":"eiusmod nisi","minValue":10}],"applicableCurrency":"GBP","sequence":0,"startValidUsagePeriod":"13:00:00"}],"type":"hourly","additionalInformation":"id"}}]}],"regulatedPlace":[{"description":"Zone 5, Kenworthy Road, All Odd, All Even","geometry":[{"version":1,"point":"SRID=27700;POINT(529157 178805)","representation":"centreLinePoint","externalReference":{"lastUpdateDate":"1981-02-08 11:30:43","UniqueStreetReferenceNumber":[{"usrn":96854586}]}}]}]}],"reference":"B2787FE2-AD74-432A-BB32-76FDB065F3E8","section":["All sections"],"traAffected":[15],"traCreator":15,"troName":"The Sample County Council (Prohibition of Waiting, Loading and Stopping) and (on-Street Parking Places) (Civil Enforcement Area) Consolidation Order 2019"}}}`

Even if this isn't a valid payload I would expect to receive some error response but it seems something's going wrong on the server before it can send me one.

**Comment by martinl-sym** [comment]
I'm also getting a 500 internal error when publishing to Integration using "createFromBody".

The JSON is below and manipulated/simplified from the 3.2.3 example d-tro on GitHub (I've done the same with 4.2.4 and got the same error)

{
    "schemaVersion": "3.2.3",
    "data": {
        "Source": {
            "actionType": "new",
            "provision": [
                {
                    "actionType": "new",
                    "orderReportingPoint": "ttroTtmoByNotice",
                    "provisionDescription": "Road Closure for Works",
                    "reference": "632",
                    "regulation": [
                        {
                            "isDynamic": false,
                            "timeZone": "Europe/London",
                            "generalRegulation": {
                                "regulationType": "miscRoadClosure"
                            },
                            "condition": [
                                {
                                    "negate": true,
                                    "vehicleCharacteristics": {
                                        "vehicleType": [
                                            "EmergencyVehicle"
                                        ]
                                    }
                                },
                                {
                                    "timeValidity": {
                                        "start": "2024-11-04T00:00:00",
                                        "end": "2025-11-03T23:59:59"
                                    },
                                    "regulationStatus": "not valid"
                                }
                            ]
                        }
                    ],
                    "regulatedPlace": [
                        {
                            "description": "From Garden Road to First Avenue/Friars Walk roundabout",
                            "geometry": {
                                "version": 1,
                                "LinearGeometry": {
                                    "direction": "bidirectional",
                                    "lateralPosition": "centreline",
                                    "linestring": "SRID=27700;LINESTRING(502151 221149,502130 221168,502091 221201,502065 221223,502054 221232,502029 221254,502026 221256,502000 221280,501981 221299,501956 221325,501930 221354,501865 221426)"
                                },
                                "externalReference": [
                                    {
                                        "lastUpdateDate": "2024-10-11 12:39:00",
                                        "UniqueStreetReferenceNumber": {
                                            "usrn": 35100494
                                        }
                                    }
                                ]
                            }
                        }
                    ]
                }
            ],
            "reference": "b9f9a497-6ade-4037-8263-be019f83efc7",
            "section": "All sections",
            "traAffected": [
                4643
            ],
            "traCreator": 4,
            "currentTraOwner": 4,
            "troName": "The council road closure from Garden Road to First Avenue/Friars Walk roundabout"
        }
    }
}

**Comment by stm-john-cooper** [comment]
Thanks for raising these issues. We have discussed separately with each of you. The 500 Internal Server Error error message is probably the wrong type of error message to be triggered by payloads containing incorrectly formatted content e.g. time and date syntax. We are working on improving our error messages and, in future, it is likely that errors of this type will be met with a 400-series error message.

**Comment by martinl-sym** [comment]
Thank you for the response. I can't believe I missed that! I've corrected this bit to put the "T" in the date/time:

"lastUpdateDate": "2024-10-11T12:39:00",

And I managed to publish to integration.

**Comment by JHB9876** [comment]
On behalf of DfT:

Error handling on the D-TRO service was "responsible" for this misleading error (error messages not correctly being displayed to users). This has been addressed.
