### ISSUE TITLE
Location Definitions 

### ISSUE THREAD

**Issue by gbkls** [department-for-transport-public/D-TRO#16]
There are three constructs used to define DTRO locations  POINT, LINESTRING and POLYGON 

It would be useful to have general overview for each type of the typical scenarios where it might be used. 

In the context of the use of DTRO data by vehicles (Automated Vehicles Bill) a Polygon seems problematic and a commentary on why Polygon definitions are needed would be particularly useful.

**Comment by JHB9876** [comment]
On behalf of DfT:

Many thanks for raising this issue.

In the first instance we suggest you take a look at https://github.com/department-for-transport-public/D-TRO/blob/main/Coding%20spatial%20referencing%20for%20Digital%20TROs%20v2.pdf which details the approach being used for spatial referencing within the D-TRO service at this time.  This note was issued 3 months ago and could do with a minor update, but the essentials are still valid. 
 
Broadly the approach is to capture TRO geometry is a flexible way (given the diversity of TROs) and several expected use cases for the data.  There is no underlying reference network model, although cross references to the National Street Gazetteer are to be provided, where streets and byways exist in the NSG. British National Grid coordinates (OSGB36) will be used. 

Further experiences through the private Beta may tune this approach.
