### ISSUE TITLE
Documentation inconsistencies for Search and Event calls

### ISSUE THREAD

**Issue by martinl-sym** [department-for-transport-public/D-TRO#17]
1)
In Search, the documentation refers to a "ta" field being mandatory. This isn't in the service definition yaml and it doesn't seem like this field is needed.

2)
In Events, if I put in a "since" date before 19th September 2024 I get an Internal Server Error. I would expect historical dates to still return everything, rather than an error.

3)
For Search, the 'page' and 'pageSize' is mandatory
For Events, the 'page', 'pageSize' and 'since' is mandatory

In the documentation, both refer to "at least one other field" being provided (e.g. traCreator).  

It's currently working without needing to provide another field. This is what we'd prefer it to (although more fine grained parameters are useful too).

As a global consumer, we'd want to get everything (using the Event search) since the last time we searched. This would be across all d-tro and therefore we wouldn't want to refine the search beyond 'since'.

**Comment by JHB9876** [comment]
On behalf of DfT:

1. We have removed the "ta" field being mandatory and this will be reflected in updates to both ICD documents (v2.2) which will be published imminently.
2. This is no longer an issue. Unless the date is in the future, no other error will come up, even if the date is today. 
3. We have updated both ICD documents (v2.2).
