### ISSUE TITLE
Inclusion of Additional TTRO Types in DTRO API

### ISSUE THREAD

**Issue by pavel-elgin** [department-for-transport-public/D-TRO#2]
## Feature Request: Addition of Missing TTRO Types to DTRO API Schema

**Description:**

As part of the ongoing integration with the DTRO API, feedback from various stakeholders, including Lincolnshire County Council, there are several TTRO (Temporary Traffic Regulation Order) types that are not currently included in the API schema. To ensure the API can support all necessary traffic regulation scenarios, we are requesting the addition of the following TTRO types:

### Proposed TTRO Types for Inclusion:
1. Road Closure
1.1 Diversion route. _Usually a road closure has a diversion route associated with it. **How should we report the road closure information?**_
2. Lane Closures: _even though lane closures are a type of a road closure, the two are very distinctive from each other and they might have different attributes (like specific lanes being closed). We think that by having the distinction between a lane closure and road closure which will allow us to for more accurate reporting of restrictions._
3. Temporary One-Way
4. Contraflow
5. Footway Closure (Link-footway closures that require a TTRO)
6. Cycle Lane Closure
7. No U-turn
8. No Left Turn
9. No Right Turn
10. Height Restriction
11. Weight Restriction
12. Width Restriction
13. Length Restriction
14. Temporary Parking Restriction
15. Suspension of Busway
16. Suspension of One-Way
17. Suspension of Parking Restriction
18. Suspension of Weight Restriction
19. Clearway/No Stopping
20. Temporary Speed Limit
21. Road Closure Crossing Point
22. Bay Suspension (for periods over 28 days that require a TTRO)
23. Temporary Parking Bay (relocation of parking bays for events, such as seasonal markets)
24. Public Right Of Way (PROW) Closure - Including extended closures beyond the initial 6-month period, as allowed by legislation.

### Open Question to Integrators/Highway authorities:
Are there any additional TTRO or related regulation types that you believe should be included in the DTRO API schema? 

### Proposed Action Items:
- Add the listed TTRO types to the DTRO API schema.
- Consider any additional suggestions from integrators regarding other TTRO types that might be necessary.

**Comment by JHB9876** [comment]
**On behalf of DfT:**
Many thanks for raising this comment.  This seems to be a reasonable request and grounds for extension of the current D-TRO data model and schema in a future iteration.

We would welcome further views or proposals from others concerning this issue.

**Comment by JHB9876** [comment]
**On behalf of DfT:**

Many thanks for this helpful input.  In the current data model the regulation types are not specifically specialised for different forms of TRO, and some of the entries in the list provided already have regulationType list entries.  However, new types have been included in a revised list. Initially, these have all been given the prefix "misc".

Proposed TTRO-related regulation types for inclusion to the regulationType list:

| Proposal | Action | Additional Entry |
|----------|--------|------------------|
| Road Closure | Add entry | miscRoadClosure | 
| Lane Closures | Add entry | miscLaneClosure | 
| Temporary One-Way | Existing entry mandatoryDirectionOneWay |  | 	
| Contraflow | Add entry | miscContraflow | 
| Footway Closure | Add entry | miscFootwayClosure | 
| Cycle Lane Closure | Add entry | miscCycleLaneClosure |  
| No U-turn | Existing entry bannedMovementNoUTurn |  | 	
| No Left Turn | Existing entry bannedMovementNoLeftTurn  |  | 	
| No Right Turn | Existing entry bannedMovementNoRightTurn |  | 	
| Height Restriction | Multiple existing entries - DimensionMaximumHeightWithTRO, DimensionMaximumHeightStructural |  | 	
| Weight Restriction | Multiple existing entries - DimensionMaximumWeightEnvironmental, DimensionMaximumWeightStructural |  | 	
| Width Restriction | Existing entry DimensionMaximumWidth |  | 	
| Length Restriction | Existing entry DimensionMaximumLength |  | 	
| Temporary Parking Restriction | Add entry | miscTemporaryParkingRestriction | 
| Suspension of Busway | Add entry | miscSuspensionOfBusway | 
| Suspension of One-Way | Add entry | miscSuspensionOfOneWay | 
| Suspension of Parking Restriction | Add entry | miscSuspensionOfParkingRestriction | 
| Suspension of Weight Restriction | Add entry | miscSuspensionOfWeightRestriction | 
| Clearway/No Stopping | Existing entry kerbsideNoStopping |  |  	
| Temporary Speed Limit | Add entry | miscTemporarySpeedLimit | 
| Road Closure Crossing Point | Add entry | miscRoadClosureCrossingPoint | 
| Bay Suspension | Add entry | miscBaySuspension | 
| Temporary Parking Bay | Add entry | miscTemporaryParkingBay | 
| Public Right Of Way (PROW) Closure | Add entry | miscPROWClosure | 

In addition, an additional entry "other" is added, to support user-defined extension of the regulationType list.

Therefore, an adjusted regulationType list would be:  

![regulationType](https://github.com/user-attachments/assets/584d70bd-e39a-4f1b-8a6f-82adfc7102ac)

Please feel free to comment.

**Comment by lizaloo** [comment]
<img width="560" alt="Screenshot 2024-09-25 at 11 55 25" src="https://github.com/user-attachments/assets/a961281b-4aa0-49e8-9e0a-6024b30c54db">
<img width="551" alt="Screenshot 2024-09-25 at 11 55 44" src="https://github.com/user-attachments/assets/cf32ed8e-12be-4843-96c6-fb6b1b5f7e98">

Thank you for the table you provided - which gave an overview of **new** TTRO regulation types you have added to the schema. The attached screenshots = where you are asking TTROs to make use of existing regulation types. We wanted to double check this assumption. TTROs are all temporary - so a "No Left Turn" in the TTRO world is a "Temporary No Left Turn" which overrides any permanent existing rules on the road network. Our assumption is that a permanent MTO will also map their "no left turn" to this regulation type. 

So our questions here at one.network are: 
- Are you sure you want permanent and temporary items to be mapped to the same element?  
- Will you have a way to map when a TTROs is "override" the permanent MTO/TROs?

FYI @pavel-elgin

**Comment by JHB9876** [comment]
**On behalf of DfT:**

As far as the data model is concerned there is no differentiation between a permanent and temporary “no left turn”, except that the OrderReportingPointType will indicate a permanent TRO for the former and TTRO for the latter.

The object “TemporaryRegulation” does allow the option to indicate that the Regulation that is the focus of the “Regulation” object is temporarily overridden another referenced Regulation.

This approach is experimental and may require some adjustment based on private Beta experiences.

**Comment by ruipinge** [comment]
@JHB9876, The `miscSuspensionOfBusway` type is currently not available in `RegulationType` enum of the [JSON Schema v3.2.3 ](https://github.com/department-for-transport-public/D-TRO/blob/main/DTRO-v3.2.3.json#L1665-L1728).

**Comment by JHB9876** [comment]
On behalf of DfT:

Many thanks for raising this. miscSuspensionOfBusway has been added to RegulationType in data specification 3.2.4.

**Comment by lizaloo** [comment]
Hi All, 
We still have a question around diversion routes. All TTROs must include a diversion route. Is this something you will want us to share via API, and if so - how? 
Thanks, 
Causeway one.network
