### ISSUE TITLE
"traAffected" in Integration - create

### ISSUE THREAD

**Issue by martinl-sym** [department-for-transport-public/D-TRO#20]
It seems like the "traAffected" in integration only includes codes 1234 and 4643.

I would expect all SWA codes to be available to test supplying d-tro for different local authorities. 

Also to ensure this is available in production.

**Comment by JHB9876** [comment]
On behalf of DfT:

We foresee expect all SWA codes to be available to test for supplying D-TRO records for different local authorities.
The D-TRO Service does not activate SWA codes for Traffic Regulation Authorities that are not already using our system (meaning they need to be onboarded as Publishers first). Therefore, if we upload a record that has a traAffected that is not already into D-TRO system, it will fail. 

Also, as an example, if you are in the systems as tra 1, you won't be able to add records for tra 2.
