### ISSUE TITLE
Samples vs specification

### ISSUE THREAD

**Issue by Karol-Kolenda** [department-for-transport-public/D-TRO#22]
In many cases, there are discrepancies between the provided samples and the JSON Schema specification. I might be mistaken, but it appears that the very core of regulation, i.e. ```regulation.condition``` in the samples from version 3.2.4 does not match the schema's ```regulation.Condition``` (starting with a capital "C") as declared in the schema.

This raises two questions:
* Since it was suggested that 3.2.4 will stay with us for a while, when can we expect these discrepancies between the samples and schema to be resolved? 
* If we proceed with the beta implementation and testing (production environment), which should take priority: the examples or the specification?

I believe this issue has been reported previously, but it still persists.

**Comment by stm-john-cooper** [comment]
Thanks for raising this issue. We apologise that there are still some inconsistencies of this type and are working to resolve them. We will get back to you with a timeline.

**Comment by JHB9876** [comment]
On behalf of DfT:

We acknowledge that there were some consistencies of object and property naming against convention in the issued schema and sample files. In data specification v3.2.4 we have sought to address issues identified and provide corrections, where these did not impact the software code base of the D-TRO Service (to respond quickly) - some inconsistencies remain and will be addressed in a future release. 

We have created a further 6 new example files where consistency is being kept in regulation.condition (i.e. the sample file matches the schema). We will upload these to GitHub shortly.

**Comment by stm-john-cooper** [comment]
Example files were added in late October. Issue closed.
