### ISSUE TITLE
dtros/Ownership endpoint

### ISSUE THREAD

**Issue by ajf2** [department-for-transport-public/D-TRO#27]
First, a consistency point - this is the only endpoint which begins with a capital letter. It should be `dtros/ownership`. I've tried calling it with the lowercase `o` and I get a 404 not found, so it is case sensitive.

Second, the ICD describes this endpoint as taking a UUID parameter called `assignToTraId`. Sending a UUID to this endpoint produces this error response:
`{
  "fault": {
    "faultstring": "OASValidation OpenAPI-Spec-Validation-1 with resource \"oas://openapi3_0.yaml\": failed with reason: \"[ERROR - Instance type (string) does not match any allowed primitive type (allowed: [\"integer\"]): [], ERROR - No request body is expected but one was found.: []]\"",
    "detail": {
      "errorcode": "steps.oasvalidation.Failed"
    }
  }
}`

Of course, `assignToTraId` should in fact be an integer.

Lastly, if I change `assignToTraId` to an integer with a value one more than the TRA ID I'm using, the response tells me that this endpoint requires the `cso` scope. If it requires one to be a central service operator, then it shouldn't be in the ICD for consumers/publishers at all.

**Comment by stm-john-cooper** [comment]
Thanks for raising this issue. We will investigate and get back to you.

**Comment by stm-john-cooper** [comment]
Access to this endpoint is now restricted to the CSO Admin team and we will issue updated documentation soon.
