### ISSUE TITLE
Inconsistency of ActionType between schema and validator

### ISSUE THREAD

**Issue by davidgruar** [department-for-transport-public/D-TRO#30]
The JSON schema v3.2.4 defines the `ActionType` enumeration thus:

```json
"ActionType": {
    "description": "List of the action types",
    "enum": [
        "new",
        "amendment",
        "fullAmend",
        "partialAmend",
        "fullRevoke",
        "partialRevoke",
        "noChange",
        "errorFix"
    ],
    "type": "string"
}
```

If I submit a D-TRO containing a Provision with an actionType of "fullAmend" I get the following error message:

> {"ruleError_0":{"name":null,"message":"Provision action type(s) has to contain one of the accepted values: new, partialAmendment, fullAmendment, partialRevoke, fullRevoke, noChange, errorFix","path":null,"rule":null}}

If I change the actionType to "fullAmendment" I can successfully submit and retrieve the D-TRO, so it would appear the schema needs updating.

The user guide (p. 17) also erroneously mentions "fullAmend" and "partialAmend", but doesn't mention "amendment" as listed in the schema.

![image](https://github.com/user-attachments/assets/4b53fed1-844f-40a9-96da-48b24e5eb730)

**Comment by stm-john-cooper** [comment]
Thanks for raising this issue @davidgruar - we agree that there is a mismatch. This will be added to improvements to be rolled out in the next release.

**Comment by JHB9876** [comment]
On behalf of DfT:

We will adjust the literals to be "fullAmendment" and "partialAmendment".
