### ISSUE TITLE
https://dtro-integration.dft.gov.uk/v1/dtros/createFromBody/  request

### ISSUE THREAD

**Issue by PJIonGis** [department-for-transport-public/D-TRO#31]
1. Provide full details of the endpoint call with parameters and body including the payload being used, e.g. ​

curl --location 'https://dtro-integration.dft.gov.uk/v1/dtros/createFromBody/' \
--header 'X-Correlation-ID: 1951578d-d88a-4cf6-a1a2-7f0614b90fd0' \
--header 'Authorization: Bearer Rk4VuDAGwkQllrn8iR0yC3Pwmh2z' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{
    "schemaVersion": "3.2.4",
    "data": {
        "Source": {
            "provision": [
                {
                    "RegulatedPlace": [
                        {
                            "geometry": {
                                "version": 1,
                                "LinearGeometry": [
                                    {
                                        "direction": "bidirectional",
                                        "lateralPosition": "onKerb",
                                        "linestring": "SRID=27700;LINESTRING(444284 333253, 444284 333253)",
                                        "representation": "linear"
                                    }
                                ],
                                "externalReference": [
                                    {
                                        "lastUpdateDate": "2024-10-01",
                                        "UniqueStreetReferenceNumber": {
                                            "usrn": 1515737
                                        }
                                    }
                                ]
                            }
                        }
                    ],
                    "regulation": [
                        {
                            "condition": [
                                {
                                    "negate": false,
                                    "regulation": [
                                        {
                                            "condition": [
                                                {
                                                    "validityCondition": [
                                                        {
                                                            "timeValidity": [
                                                                {
                                                                    "start": "2024-08-01T08:00:00",
                                                                    "validPeriod": [
                                                                        {
                                                                            "recurringDayWeekMonthPeriod": [
                                                                                {
                                                                                    "applicableDay": [
                                                                                        "monday",
                                                                                        "tuesday",
                                                                                        "wednesday",
                                                                                        "thursday",
                                                                                        "friday",
                                                                                        "saturday"
                                                                                    ]
                                                                                }
                                                                            ],
                                                                            "recurringTimePeriodOfDay": [
                                                                                {
                                                                                    "startTimeOfPeriod": "08:00:00",
                                                                                    "endTimeOfPeriod": "18:00:00"
                                                                                }
                                                                            ]
                                                                        }
                                                                    ]
                                                                }
                                                            ]
                                                        }
                                                    ]
                                                }
                                            ]
                                        }
                                    ]
                                }
                            ],
                            "isDynamic": false,
                            "timeZone": "Europe/London"
                        }
                    ],
                    "actionType": "new",
                    "orderReportingPoint": "permanentNoticeOfMaking",
                    "provisionDescription": "Schedule 1: No Waiting Monday to Saturday, 8am to 6pm",
                    "reference": "A3448229-1DFA-48CD-A785-376ACB9F7C56"
                }
            ],
            "actionType": "new",
            "currentTraOwner": 6915,
            "reference": "B2787FE2-AD74-432A-BB32-76FDB065F3E8",
            "section": "Schedule 1",
            "traAffected": [
                6915
            ],
            "traCreator": 6915,
            "troName": "DfT Example - Oct. 2024 - partial extract of THE DERBYSHIRE COUNTY COUNCIL (MARKET STREET AND TOWN END ROAD, DRAYCOTT) (RESTRICTION AND LIMITED WAITING) TRAFFIC REGULATION ORDER 2024 (DfT mockup)"
        }
    }
}'

2. Provide full error message from D-TRO application, e.g.​

{
    "ruleError_0": {
        "name": null,
        "message": "TRA '3' cannot add/update a DTRO for another TRA. (creator TRA is '6915', owner TRA is '6915' )",
        "path": null,
        "rule": null
    },
    "ruleError_1": {
        "name": null,
        "message": "One or more TRA affected is not in our records.",
        "path": null,
        "rule": null
    }
}

3. Provide the date and time of the API call to enable us to search to logs for more information​
06/11/24 13:21

4. Provide expected and actual behaviour​

Expected behaviour - example added to database
Actual behaviour - Error message

5. Provide steps to reproduce

![s1](https://github.com/user-attachments/assets/9ff44cf3-48b6-4899-9ce1-4c1a32d2744a)

![s2](https://github.com/user-attachments/assets/7c67543c-9d58-419b-99e0-7d41b70e08fa)

![s3](https://github.com/user-attachments/assets/fb6a1aa7-5400-434d-9ec0-cbc932e6dddf)

6. Provide what version of Schema you are using​
3.2.4

7. Provide any additional context, if applicable

We have used DfT's Example Oct 2024 partial extract, but we are getting error messages.
Please correct error message or explain why it is appearing

**Comment by GaTilley** [comment]
In the example file the TRA ID need to be changed to your ID. So for yourself, change all references to “6915” (e.g. currentTraOwner, traAffected, traCreator) to “3” in the sample file. See below extract:



"currentTraOwner": 6915,
"reference": "B2787FE2-AD74-432A-BB32-76FDB065F3E8",
"section": "Schedule 1",
"traAffected": [
6915
],
"traCreator": 6915

**Comment by stm-john-cooper** [comment]
This issue has been confirmed as resolved.
