### ISSUE TITLE
Missing regulationType in JSON-3.2.4-example-Derbyshire 2024 DJ388 partial.json

### ISSUE THREAD

**Issue by Karol-Kolenda** [department-for-transport-public/D-TRO#33]
I'm sorry if this is a basic question, but is there a specific reason why the JSON-3.2.4-example-Derbyshire-2024-DJ388-partial.json file is missing the regulationType property? Based on the schedule description, it seems like this property should be set to kerbsideLimitedWaiting.

**Comment by JHB9876** [comment]
On behalf of DfT:

We will take a look and come back to you. Many thanks for raising the issue.

**Comment by JHB9876** [comment]
On behalf of DfT:

You are quite correct. We will resolve this in this sample and reissue.

**Comment by JHB9876** [comment]
On behalf of DfT:

Corrected example file posted to GitHub.
