### ISSUE TITLE
Publication issue with AccessConditionType condition

### ISSUE THREAD

**Issue by janicki95** [department-for-transport-public/D-TRO#35]
When publishing a source that contains a "accessConditionType" condition, the service returns error code 500 with the following error:

```
{
    "message": "Internal Server Error",
    "error": "An unexpected error occurred: The JSON value could not be converted to System.Collections.Generic.List`1[System.String]. Path: $.accessConditionType | LineNumber: 0 | BytePositionInLine: 44."
}
```

"accessConditionType":

```
{
    "accessConditionType": "loadingAndUnloading",
    "negate": false
}
```

**Comment by MehrajRM** [comment]
Hi Patryk,

Please could you provide the full payload and the full command that you are using? Many thanks

**Comment by stm-john-cooper** [comment]
The square brackets are missing around the loadingAndUnloading. It should be:

```
{
    "accessConditionType": "[loadingAndUnloading]",
    "negate": false
}
```

I have successfully parsed my own customised version of your order into the INT environment with the above amendment.

**Comment by stm-john-cooper** [comment]
Closing as completed but let us know if any problems persist.

**Comment by davidgruar** [comment]
@stm-john-cooper I assume the square brackets in your example should go outside the quotes rather than inside? `["loadingAndUnloading"]` not `"[loadingAndUnloading]"`.

**Comment by stm-john-cooper** [comment]
Yes, correct. Sorry, should be:
```
                                                                                                                {
                                                            "accessConditionType": ["loadingAndUnloading"],
                                                            "negate": false
                                                        },
```

**Comment by stm-john-cooper** [comment]
Fixed in the above thread too - just in case others don't look this far down.
