### ISSUE TITLE
Closed Consultations

### ISSUE THREAD

**Issue by davidgruar** [department-for-transport-public/D-TRO#41]
Is the Consultations array supposed to include completed consultations for made TROs, as well as current or future ones for proposed TROs? If so, are the properties relating to comments (`howToComment`, `pointOfContactAddress` and `pointOfContactEmail`) still relevant, or should they be omitted if the consultation is closed?

**Comment by JHB9876** [comment]
On behalf of DfT: 

The expectation, subject to secondary legislation following consultation, is that information on consultations would be made at the time of the notice of proposals (i.e. commencement of consultation). There is no expected requirement for the provision of information concerning consultations at other points in the lifecycle, at this time.
