### ISSUE TITLE
V3.3.0 Release Announcement 

### ISSUE THREAD

**Issue by JHB9876** [department-for-transport-public/D-TRO#42]
On behalf of DfT:  

DfT announce that they will be upgrading the D-TRO Service in line with the v3.3.0 release of the D-TRO Data Specification on 28 November 2024. 

Documentation and artefacts for v3.3.0 will be posted to GitHub when they are available, shortly, in advance of the upgrade.   

Although we are finalising v3.3.0 of the D-TRO Data Specification the following modifications are expected to be included.  

1. Clarifying relationships between some key objects and their "children" objects, to improve consistency of the Data Specification - notably "Regulation", "Geometry", and "Condition". [Clarify JSON modelling of inheritance hierarchies · Issue #25](https://github.com/department-for-transport-public/D-TRO/issues/25) - Partially addressed 
 

2. In v3.3.0 “TimeValidity” is defined as a sub-type of "Condition". This removes the direct relationship between “TimeValidity” and “Regulation.”  [Circular references between ValidityCondition and TimeValidity? · Issue #14 ](https://github.com/department-for-transport-public/D-TRO/issues/14) 

3.	Provision of improved TRO samples, notably concerning Conditions and Geometry. 

4.	Request from TfL concerning additional RegulationTypes for red routes - addition of “kerbsideSingleRedLines”, “kerbsideDoubleRedLines”. [Additional Regulation Types - Issue #34](https://github.com/department-for-transport-public/D-TRO/issues/34) 

5.	D-TRO Service codebase updates to make the Service agnostic to the order of Properties. 

6.	Clarify the use of multiple versions of geometries, including a sample file showing expected behaviour. 

7.	Correct error in the Association names for "periodEnd" and "periodStart" are wrong way round relation to "ChangeableTimePeriod".  

8.	Data model and schema updates to match the existing validation of ActionType (from "partialAmend" to "partialAmendment" and "fullAmend" to "fullAmendment"). 

9.	Capability for recording Diversion Routes added.

**Comment by PeterDLowe** [comment]
If we have a consolidation order with say 4000 restriction items in 1 order of which 2300 are NWAAT restrictions and the Client wants to amend or revoke 1 of the 2300, what will be the mechanism for this. Will the DSP simply change the 1 item and the resubmit the whole 4001 items to the hub? otherwise how will there be an identifier for resubmitting just the 1 item? I am thinking of variation orders in particular but this will apply to TTRO's as well in some instances.

**Comment by stm-john-cooper** [comment]
@mikebartlett1 the main part of the next Technical Webinar on 27 November will be around explaining the content of the version 3.3.0 update including the provision of diversion route information.

**Comment by JHB9876** [comment]
On behalf of DfT:

Version 3.3.0 of the D-TRO Data Specification has been released. Please see issue #1 for more information.
