### ISSUE TITLE
Deleting of D-TRO 

### ISSUE THREAD

**Issue by Karol-Kolenda** [department-for-transport-public/D-TRO#43]
Quick question (not feature request): 

Does the following action:
`D6 
DELETE /v1/dtros/{id} 
Delete a D-TRO by D-TRO ID`

completely remove D-TRO, so it will no longer be accessible through any queries or in history?

**Comment by JHB9876** [comment]
On behalf of DfT: 
 
The DELETE endpoint does support the deletion of a previously submitted D-TRO record. This is a soft delete, such that the record is flagged as deleted in the database. 
 
SEARCH endpoint will not return a deleted D-TRO record.  
 
The creation and deletion events of subsequently deleted D-TRO can be seen via the EVENTS endpoint. 
 
The D-TRO service does not offer a capability to retrieve deleted records.

**Comment by Karol-Kolenda** [comment]
Thank you, that is very helpful.
