### ISSUE TITLE
Server internal error 

### ISSUE THREAD

**Issue by PJIonGis** [department-for-transport-public/D-TRO#48]
Hello

Got problem today was testing few things, but i get that response:
With Internal Server error (500)
An error occurred: The given key 'Message' was not present in the dictionary.

So what i did i took one of stuff what passed  like week ago change refrence numbers and try to post it  again and get that error. Its me or its somthing with server side?
Below i give u full details  again same thing last week was ok now i get that message tryed diffrente examples data and still same response. 

I got also like follow question do source its only singular object or it can be array o objects like is with provsion nesting object? Acording to deocumentation 'In each D-TRO record, it is possible to define one or many Source objects, with each Source object being
related to one section or clause in the TRO.' 
1.
<pre>curl --location 'https://dtro-integration.dft.gov.uk/v1/dtros/createFromBody/' \
--header 'X-Correlation-ID: 1951578d-d88a-4cf6-a1a2-7f0614b90fd0' \
--header 'Authorization: Bearer *********************************' \
--header 'Accept: application/json' \
--header 'Content-Type: application/json' \
--data '{   
    "schemaVersion": "3.2.4",
    "data": {
        "source": {
            "section": "All sections",
            "troName": "DfT Example - TTRO weight restriction v1, Oct. 2024",
            "provision": [
                {
                    "reference": "not working",
                    "actionType": "new",
                    "regulation": [
                        {
                            "timeZone": "Europe/London",
                            "condition": [
                                {
                                    "timeValidity": {
                                        "end": "2024-11-29T18:00:00",
                                        "start": "2024-08-01T08:00:00"
                                    }
                                },
                                {
                                    "vehicleCondition": {
                                        "vehicleCharacteristics": {
                                            "maximumGrossWeightCharacteristic": {
                                                "typeOfWeight": "maximumPermitted",
                                                "grossVehicleWeight": 2
                                            }
                                        }
                                    }
                                }
                            ],
                            "isDynamic": false,
                            "generalRegulation": {
                                "regulationType": "dimensionMaximumWeightStructural"
                            }
                        }
                    ],
                    "regulatedPlace": [
                        {
                            "geometry": {
                                "version": 1,
                                "linearGeometry": {
                                    "direction": "bidirectional",
                                    "linestring": "SRID=27700;LINESTRING(320620 124993, 320621 124997, 320625 125007)",
                                    "representation": "representingZone",
                                    "lateralPosition": "centreline"
                                },
                                "externalReference": [
                                    {
                                        "lastUpdateDate": "2024-08-01 00:00:00",
                                        "uniqueStreetReferenceNumber": {
                                            "usrn": 39605836
                                        }
                                    }
                                ]
                            },
                            "description": "Netherclay Bridge, Bishops Hull, Taunton"
                        }
                    ],
                    "orderReportingPoint": "ttroTtmoNoticeOfIntention",
                    "provisionDescription": "Polskie byli tu"
                }
            ],
            "reference": "testm3",
            "actionType": "new",
            "traCreator": 3,
            "traAffected": [
                3
            ],
            "currentTraOwner": 3
        }
    }
}</pre>

2. Provide full error message from D-TRO application

An error occurred: The given key 'Message' was not present in the dictionary.
 
3. Provide the date and time of the API call to enable us to search to logs for more information
 27/11/2024 12:40
4 Provide expected and actual behaviour
Well i except id in return

PJ

**Comment by stm-john-cooper** [comment]
Thanks for raising this issue. I have replicated the error message that you have received. We are investigating what might be causing this problem. It may be something that will be rectified when v3.3.0 is launched. We will get back to you.

**Comment by PJIonGis** [comment]
Hey John

Looks like after you make live scheme 3.3.0 i used some 3.3.0  example and get id in return 
So looks like somthing is with validation on on 3.2.4. That example from top still generate same error on 3.3.0 so  the old examples mytbe no longer valid.(just blaind quess but it mytbe my error  hehe with that example:>)


PJ

**Comment by PJIonGis** [comment]
ok i found what was wrong:>
the obj names are  case sensitive when u send it i.e Source and Provision r capitals.
when u recive obj its source etc... u get source etc... small letter
Dont know its intended but any way resend data with small letter  like source generate respond with that error:>

PJ

**Comment by stm-john-cooper** [comment]
Well done @PJIonGis. I capitalised "Source" but it's still lowercase "provision". Changing these triggered a different error about geometry and I changed it to "LinearGeometry". I was then able to successfully post your payload - see full edited version below. 

```
{   
    "schemaVersion": "3.2.4",
    "data": {
        "Source": {
            "section": "All sections",
            "troName": "DfT Example - TTRO weight restriction v1, Oct. 2024",
            "provision": [
                {
                    "reference": "not working",
                    "actionType": "new",
                    "regulation": [
                        {
                            "timeZone": "Europe/London",
                            "condition": [
                                {
                                    "timeValidity": {
                                        "end": "2024-11-29T18:00:00",
                                        "start": "2024-08-01T08:00:00"
                                    }
                                },
                                {
                                    "vehicleCondition": {
                                        "vehicleCharacteristics": {
                                            "maximumGrossWeightCharacteristic": {
                                                "typeOfWeight": "maximumPermitted",
                                                "grossVehicleWeight": 2
                                            }
                                        }
                                    }
                                }
                            ],
                            "isDynamic": false,
                            "generalRegulation": {
                                "regulationType": "dimensionMaximumWeightStructural"
                            }
                        }
                    ],
                    "regulatedPlace": [
                        {
                            "geometry": {
                                "version": 1,
                                "LinearGeometry": {
                                    "direction": "bidirectional",
                                    "linestring": "SRID=27700;LINESTRING(320620 124993, 320621 124997, 320625 125007)",
                                    "representation": "representingZone",
                                    "lateralPosition": "centreline"
                                },
                                "externalReference": [
                                    {
                                        "lastUpdateDate": "2024-08-01 00:00:00",
                                        "uniqueStreetReferenceNumber": {
                                            "usrn": 39605836
                                        }
                                    }
                                ]
                            },
                            "description": "Netherclay Bridge, Bishops Hull, Taunton"
                        }
                    ],
                    "orderReportingPoint": "ttroTtmoNoticeOfIntention",
                    "provisionDescription": "Polskie byli tu"
                }
            ],
            "reference": "testm3",
            "actionType": "new",
            "traCreator": 586,
            "traAffected": [
                586
            ],
            "currentTraOwner": 586
        }
    }
}
```

**Comment by PJIonGis** [comment]
Hey John

Yea i overcome that also, but i've noticed something weird about scheme
3.3.0.
So i passed some single provision stuff but iv notice that u change there
objects structure (look at examples provide for 3.3.0) u removed geometry
object and then geometry attribute 'version; u put in Linstring polygamy
etc object,
not a big problem, don't know if u intend to do this, in new scheme (3.3.0)
(Nothing about it new model pdf)
More concern im that on 3.3.0 when u try pass more then one provision in
array i get some weird rule errors starting that i can have only one
regulation but crealy in model u can have one but per provision
All good in 3.2.4 when i do same dtro
Anyway I'm now testing on 3.2.4 pretty intensively probably you'll see in
logs delatings uploading. Thats cos im checking  all ui and converter from
attribute table oriented json (arc or qgis) to your object schema
Example : form that wording No Stopping Mon-Fri 8am-6pm get your provision
object and that's some shit:>

PJ
