### ISSUE TITLE
Consider relaxing auth for health check endpoints

### ISSUE THREAD

**Issue by ajf2** [department-for-transport-public/D-TRO#49]
Currently, if you use the `healthApi` endpoint without first obtaining an access token, you get an HTTP 401 Unauthorized response with a response body such as `{"fault":{"faultstring":"Invalid access token","detail":{"errorcode":"oauth.v2.InvalidAccessToken"}}}`.

I think it would be sensible not to require auth on the `healthApi` and `healthDatabase` endpoints, given that they only let users know if things are working normally. They should of course still work if the caller has passed a valid access token (perhaps even an invalid access token).

As a DSP, if we were to have a process checking the responses from these endpoints it would currently need to use the access credentials of one of our TRA customers, which could perhaps skew any metrics and reporting on API usage you have. An alternative would be for us to set up another app on the Apigee portal with only data consumer rights, then use the credentials for that.

**Comment by stm-john-cooper** [comment]
Thanks for this suggestion but we are unable to leave an endpoint without the full level of security. We suggest that you apply to become an Integration or Production Consumer as you suggest.
