### ISSUE TITLE
Request for Additional JSON Examples for Other TTRO Types

### ISSUE THREAD

**Issue by pavel-elgin** [department-for-transport-public/D-TRO#5]
Dear Maintainers,

Firstly, thank you for your efforts in developing and maintaining the Digital Traffic Regulation Orders (DTRO) project. The repository and its documentation have been very useful in understanding and implementing TTROs.

However, I would like to request an enhancement to the repository's documentation. Currently, the available JSON examples primarily cover a limited set of TTRO types. To make it easier for users to implement and validate other TTRO types, it would be highly beneficial if additional JSON examples for the following TTRO types could be provided:

1. **Road Closures**
2. **Temporary One-Way**
4. **Height Restriction**
5. **Weight Limits**
6. **Suspension of One-Way**

These examples would help provide clarity on the structure and specific fields that need to be included for each of these TTRO types. Such examples would not only aid in proper implementation but also ensure consistency across different implementations by various users.

If possible, could these examples be added to the documentation or provided as part of the examples directory in the repository?

Thank you for considering this request, and I look forward to any updates on this matter.

Best regards,  
Pavel

**Comment by gbkls** [comment]
Following this up 

Currently the integration environment seems to only have a single  record 

For this type of project you really need a large number of integration test records covering many scenarios to effectively test operation. 

Hope to see more data sets uploaded 

George

**Comment by ruipinge** [comment]
Is there any news on this issue? Some real-life TTRO examples in the D-TRO JSON format would be of incredible help!

**Comment by stm-john-cooper** [comment]
@ruipinge Yes, we still plan to create new TTRO example files. Please bear with us as there are lots of competing priorities. However, we are pleased to note that data is now starting to be published on the service.

**Comment by Karol-Kolenda** [comment]
Any progress with this ticket? Since deadlines are quite tight at the moment, and this issue was created in August, when can we expect some more samples here?

**Comment by stm-john-cooper** [comment]
Sorry for the delay. These example files have been created, are going through final checks and will be published very soon.

**Comment by Karol-Kolenda** [comment]
Thank you, John, much appreciate it. The examples are much easier to follow then JSON Schema (which is required, but not easy to digest), hence my query.
