### ISSUE TITLE
USRN usage

### ISSUE THREAD

**Issue by Karol-Kolenda** [department-for-transport-public/D-TRO#52]
**Subject:** Clarification on USRN Usage and Street Gazetteer Integration

This is a query, not a feature request.

I believe using USRN to establish a connection between DTRO provisions and street gazetteers is highly beneficial. However, I have two questions regarding its implementation:

1. **Provisions Spanning Multiple Streets:**  
   Is it correct to assume that when a provision spans multiple streets, all relevant streets should be referenced in the `externalReferences` array?

2. **Handling Streets Without Allocated USRNs:**  
   In cases where streets do not have allocated USRNs because they are not part of the gazetteer, what approach is recommended? For example, some of our customers record provisions for locations such as "GARAGES BEHIND MAPLE ROAD" or "SERVICE ROAD TO SANTA CLAUS AVENUE."  

   In such scenarios, should the `externalReferences` array:  
   a) Contain unofficial/dummy USRNs (commonly used by gazetteer custodians for internal systems), even if they are meaningless outside the authority?  
   b) Depend on the street gazetteer custodian to add all roads to the LSG?  
   c) Consider dropping the "required" flag in the `externalReference` array or the `UniqueStreetReferenceNumber` field?  

For point 2, I am open to any solution but am curious to understand the recommended approach.

Thank you for your guidance.

**Comment by JHB9876** [comment]
On behalf of DfT: 

**1 Provisions spanning multiple streets** 

Yes, all relevant streets, via their USRN, shall be referenced in the ExternalReferences array. 

**2 Handling street without allocated USRNs** 

Formally within the data model and schema, ExternalReference is optional. Where USRNs do exist, they are expected to be supplied. 

If no USRN is available, ExternalReference is not required.  

Only USRNs, street names and street numbers occurring in the NSG shall be supplied. 

We are considering a future extension to the data model to allow other forms of reference and additional information to be supplied. This has been added to our backlog for review.
