### ISSUE TITLE
TemporaryRegulation object required section typo (v.3.3.0)

### ISSUE THREAD

**Issue by bashir-magomedov** [department-for-transport-public/D-TRO#59]
Hi team,

TemporaryRegulation defines "temporarilyOverriddenProvision" as one of its properties but then "required" section calls this property "temporaryOverridenProvision".

I.e. "temporarilyOverriddenProvision" 
vs "temporaryOverridenProvision"

Can you fix it pls?

**Comment by JHB9876** [comment]
On behalf of DfT:

Yes! This object would be better called TemporaryProvision, rather than TemporaryRegulation. We will aim to address this in a future release.
