### ISSUE TITLE
JSON Schema v3.2.2 has some invalid references

### ISSUE THREAD

**Issue by ruipinge** [department-for-transport-public/D-TRO#8]
* **Describe the bug**

The type `ChangeableTimePeriodEnd` includes some references to other types under the `definitions` path that doesn't exist. The types are available under the path `$defs`.

* **Tell us how to reproduce the error**

1. Validate `DTRO-v3.2.2.json` JSON Schema with a validation tool.
2. See error

* **Expected behavior**

The validation should pass.

* **Platform**

Were you running the code on:

- [x] Your network laptop
- [ ] Citrix
- [ ] Non-network laptop
- [ ] Other platform (please specify)

* **Screenshots**

<img width="876" alt="image" src="https://github.com/user-attachments/assets/aaae4eeb-6d14-4256-babf-9a86495b6d8b">

**Comment by JHB9876** [comment]
On behalf of DfT: 

Many thanks for raising these issues. The DfT D-TRO team have been reviewing and expect to imminently issue a data specification release (v3.2.4) which aims to address the issues raised.

**Comment by JHB9876** [comment]
On behalf of DfT:

Again, many thanks for raising these issues.  Many of the issues raised have been addressed in the data specification release 3.2.4. In a small number of cases, the correction requires a code base change to the D-TRO Service and we have recorded the issue and resolution and will address in a future release of the data specification.
